/**
 * Relation graph for Drizzle's `with` queries -- the equivalent of Prisma's
 * `include`.
 *
 * Generated by drizzle-kit, then renamed where introspection disagreed with the
 * domain. Introspection names a relation after the table it points at, so
 * bookings.agentId became `user` and booking guests became `bookingGuests`;
 * Prisma named them `agent` and `guests`, and those names are what the
 * services, the API responses and the admin UI already use. Renaming them here
 * means nothing downstream has to know the ORM changed.
 */
import { relations } from "drizzle-orm/relations";
import { agencies, users, userRoles, roles, rolePermissions, permissions, hotels, hotelImages, hotelAmenities, amenities, roomTypes, roomTypeImages, roomTypeAmenities, rooms, roomRates, ratePlans, customers, customerDocuments, bookings, bookingRooms, bookingGuests, bookingServices, services, bookingStatusHistory, payments, refunds, invoices, invoiceItems, destinations, tourPackages, tourImages, tourItineraries, tourBookings, vehicles, drivers, transportBookings, commissions, notifications, auditLogs, settings } from "./schema.js";

export const usersRelations = relations(users, ({one, many}) => ({
	agency: one(agencies, {
		fields: [users.agencyId],
		references: [agencies.id]
	}),
	userRoles: many(userRoles),
	customers: many(customers),
	bookings: many(bookings),
	bookingRooms_checkedInById: many(bookingRooms, {
		relationName: "bookingRooms_checkedInById_users_id"
	}),
	bookingRooms_checkedOutById: many(bookingRooms, {
		relationName: "bookingRooms_checkedOutById_users_id"
	}),
	bookingStatusHistories: many(bookingStatusHistory),
	commissions: many(commissions),
	notifications: many(notifications),
	auditLogs: many(auditLogs),
}));

export const agenciesRelations = relations(agencies, ({many}) => ({
	users: many(users),
	hotels: many(hotels),
	settings: many(settings),
}));

export const userRolesRelations = relations(userRoles, ({one}) => ({
	user: one(users, {
		fields: [userRoles.userId],
		references: [users.id]
	}),
	role: one(roles, {
		fields: [userRoles.roleId],
		references: [roles.id]
	}),
}));

export const rolesRelations = relations(roles, ({many}) => ({
	userRoles: many(userRoles),
	rolePermissions: many(rolePermissions),
}));

export const rolePermissionsRelations = relations(rolePermissions, ({one}) => ({
	role: one(roles, {
		fields: [rolePermissions.roleId],
		references: [roles.id]
	}),
	permission: one(permissions, {
		fields: [rolePermissions.permissionId],
		references: [permissions.id]
	}),
}));

export const permissionsRelations = relations(permissions, ({many}) => ({
	rolePermissions: many(rolePermissions),
}));

export const hotelsRelations = relations(hotels, ({one, many}) => ({
	agency: one(agencies, {
		fields: [hotels.agencyId],
		references: [agencies.id]
	}),
	images: many(hotelImages),
	hotelAmenities: many(hotelAmenities),
	roomTypes: many(roomTypes),
	bookings: many(bookings),
}));

export const hotelImagesRelations = relations(hotelImages, ({one}) => ({
	hotel: one(hotels, {
		fields: [hotelImages.hotelId],
		references: [hotels.id]
	}),
}));

export const hotelAmenitiesRelations = relations(hotelAmenities, ({one}) => ({
	hotel: one(hotels, {
		fields: [hotelAmenities.hotelId],
		references: [hotels.id]
	}),
	amenity: one(amenities, {
		fields: [hotelAmenities.amenityId],
		references: [amenities.id]
	}),
}));

export const amenitiesRelations = relations(amenities, ({many}) => ({
	hotelAmenities: many(hotelAmenities),
	roomTypeAmenities: many(roomTypeAmenities),
}));

export const roomTypesRelations = relations(roomTypes, ({one, many}) => ({
	hotel: one(hotels, {
		fields: [roomTypes.hotelId],
		references: [hotels.id]
	}),
	images: many(roomTypeImages),
	amenities: many(roomTypeAmenities),
	rooms: many(rooms),
	roomRates: many(roomRates),
	bookingRooms: many(bookingRooms),
}));

export const roomTypeImagesRelations = relations(roomTypeImages, ({one}) => ({
	roomType: one(roomTypes, {
		fields: [roomTypeImages.roomTypeId],
		references: [roomTypes.id]
	}),
}));

export const roomTypeAmenitiesRelations = relations(roomTypeAmenities, ({one}) => ({
	roomType: one(roomTypes, {
		fields: [roomTypeAmenities.roomTypeId],
		references: [roomTypes.id]
	}),
	amenity: one(amenities, {
		fields: [roomTypeAmenities.amenityId],
		references: [amenities.id]
	}),
}));

export const roomsRelations = relations(rooms, ({one, many}) => ({
	roomType: one(roomTypes, {
		fields: [rooms.roomTypeId],
		references: [roomTypes.id]
	}),
	bookingRooms: many(bookingRooms),
}));

export const roomRatesRelations = relations(roomRates, ({one}) => ({
	roomType: one(roomTypes, {
		fields: [roomRates.roomTypeId],
		references: [roomTypes.id]
	}),
	ratePlan: one(ratePlans, {
		fields: [roomRates.ratePlanId],
		references: [ratePlans.id]
	}),
}));

export const ratePlansRelations = relations(ratePlans, ({many}) => ({
	roomRates: many(roomRates),
}));

export const customersRelations = relations(customers, ({one, many}) => ({
	user: one(users, {
		fields: [customers.userId],
		references: [users.id]
	}),
	documents: many(customerDocuments),
	bookings: many(bookings),
	tourBookings: many(tourBookings),
}));

export const customerDocumentsRelations = relations(customerDocuments, ({one}) => ({
	customer: one(customers, {
		fields: [customerDocuments.customerId],
		references: [customers.id]
	}),
}));

export const bookingsRelations = relations(bookings, ({one, many}) => ({
	hotel: one(hotels, {
		fields: [bookings.hotelId],
		references: [hotels.id]
	}),
	customer: one(customers, {
		fields: [bookings.customerId],
		references: [customers.id]
	}),
	agent: one(users, {
		fields: [bookings.agentId],
		references: [users.id]
	}),
	bookingRooms: many(bookingRooms),
	guests: many(bookingGuests),
	services: many(bookingServices),
	statusHistory: many(bookingStatusHistory),
	payments: many(payments),
	invoices: many(invoices),
	commissions: many(commissions),
}));

export const bookingRoomsRelations = relations(bookingRooms, ({one}) => ({
	booking: one(bookings, {
		fields: [bookingRooms.bookingId],
		references: [bookings.id]
	}),
	room: one(rooms, {
		fields: [bookingRooms.roomId],
		references: [rooms.id]
	}),
	roomType: one(roomTypes, {
		fields: [bookingRooms.roomTypeId],
		references: [roomTypes.id]
	}),
	user_checkedInById: one(users, {
		fields: [bookingRooms.checkedInById],
		references: [users.id],
		relationName: "bookingRooms_checkedInById_users_id"
	}),
	user_checkedOutById: one(users, {
		fields: [bookingRooms.checkedOutById],
		references: [users.id],
		relationName: "bookingRooms_checkedOutById_users_id"
	}),
}));

export const bookingGuestsRelations = relations(bookingGuests, ({one}) => ({
	booking: one(bookings, {
		fields: [bookingGuests.bookingId],
		references: [bookings.id]
	}),
}));

export const bookingServicesRelations = relations(bookingServices, ({one}) => ({
	booking: one(bookings, {
		fields: [bookingServices.bookingId],
		references: [bookings.id]
	}),
	service: one(services, {
		fields: [bookingServices.serviceId],
		references: [services.id]
	}),
}));

export const servicesRelations = relations(services, ({many}) => ({
	bookingServices: many(bookingServices),
}));

export const bookingStatusHistoryRelations = relations(bookingStatusHistory, ({one}) => ({
	booking: one(bookings, {
		fields: [bookingStatusHistory.bookingId],
		references: [bookings.id]
	}),
	changedBy: one(users, {
		fields: [bookingStatusHistory.changedById],
		references: [users.id]
	}),
}));

export const paymentsRelations = relations(payments, ({one, many}) => ({
	booking: one(bookings, {
		fields: [payments.bookingId],
		references: [bookings.id]
	}),
	refunds: many(refunds),
}));

export const refundsRelations = relations(refunds, ({one}) => ({
	payment: one(payments, {
		fields: [refunds.paymentId],
		references: [payments.id]
	}),
}));

export const invoicesRelations = relations(invoices, ({one, many}) => ({
	booking: one(bookings, {
		fields: [invoices.bookingId],
		references: [bookings.id]
	}),
	items: many(invoiceItems),
}));

export const invoiceItemsRelations = relations(invoiceItems, ({one}) => ({
	invoice: one(invoices, {
		fields: [invoiceItems.invoiceId],
		references: [invoices.id]
	}),
}));

export const tourPackagesRelations = relations(tourPackages, ({one, many}) => ({
	destination: one(destinations, {
		fields: [tourPackages.destinationId],
		references: [destinations.id]
	}),
	images: many(tourImages),
	itineraries: many(tourItineraries),
	tourBookings: many(tourBookings),
}));

export const destinationsRelations = relations(destinations, ({many}) => ({
	tourPackages: many(tourPackages),
}));

export const tourImagesRelations = relations(tourImages, ({one}) => ({
	tourPackage: one(tourPackages, {
		fields: [tourImages.tourPackageId],
		references: [tourPackages.id]
	}),
}));

export const tourItinerariesRelations = relations(tourItineraries, ({one}) => ({
	tourPackage: one(tourPackages, {
		fields: [tourItineraries.tourPackageId],
		references: [tourPackages.id]
	}),
}));

export const tourBookingsRelations = relations(tourBookings, ({one}) => ({
	tourPackage: one(tourPackages, {
		fields: [tourBookings.tourPackageId],
		references: [tourPackages.id]
	}),
	customer: one(customers, {
		fields: [tourBookings.customerId],
		references: [customers.id]
	}),
}));

export const driversRelations = relations(drivers, ({one, many}) => ({
	vehicle: one(vehicles, {
		fields: [drivers.vehicleId],
		references: [vehicles.id]
	}),
	transportBookings: many(transportBookings),
}));

export const vehiclesRelations = relations(vehicles, ({many}) => ({
	drivers: many(drivers),
	transportBookings: many(transportBookings),
}));

export const transportBookingsRelations = relations(transportBookings, ({one}) => ({
	vehicle: one(vehicles, {
		fields: [transportBookings.vehicleId],
		references: [vehicles.id]
	}),
	driver: one(drivers, {
		fields: [transportBookings.driverId],
		references: [drivers.id]
	}),
}));

export const commissionsRelations = relations(commissions, ({one}) => ({
	// Named `agent`, not `user`: introspection names a relation after the target
	// table, but the API has always returned this as `agent` and the admin UI
	// reads commission.agent.
	agent: one(users, {
		fields: [commissions.agentId],
		references: [users.id]
	}),
	booking: one(bookings, {
		fields: [commissions.bookingId],
		references: [bookings.id]
	}),
}));

export const notificationsRelations = relations(notifications, ({one}) => ({
	user: one(users, {
		fields: [notifications.userId],
		references: [users.id]
	}),
}));

export const auditLogsRelations = relations(auditLogs, ({one}) => ({
	user: one(users, {
		fields: [auditLogs.userId],
		references: [users.id]
	}),
}));

export const settingsRelations = relations(settings, ({one}) => ({
	agency: one(agencies, {
		fields: [settings.agencyId],
		references: [agencies.id]
	}),
}));