import 'dotenv/config';

/**
 * The schema in src/db/schema.js is generated by `drizzle-kit pull`, which
 * introspects the live database, so it reflects what is actually deployed --
 * column types, numeric precision, enum values and nullability included.
 * `drizzle-kit generate` then diffs it to produce migrations, which
 * src/db/migrate.js applies.
 */
export default {
  dialect: 'postgresql',
  schema: './src/db/schema.js',
  out: './src/db/migrations',
  dbCredentials: {
    url: process.env.DATABASE_URL,
  },
  casing: 'snake_case',
};
