import 'dotenv/config';

/**
 * The schema in src/db/schema.js is generated by `drizzle-kit pull`, which
 * introspects the live database rather than being hand-written from
 * prisma/schema.prisma. That way it reflects what is actually deployed --
 * column types, numeric precision, enum values and nullability included --
 * instead of my reading of the Prisma file.
 */
export default {
  dialect: 'postgresql',
  schema: './src/db/schema.js',
  out: './src/db/migrations',
  dbCredentials: {
    url: process.env.DATABASE_URL,
  },
  casing: 'snake_case',
};
