/**
 * Drizzle schema, generated by `drizzle-kit pull` against the live database so
 * it reflects what is actually deployed -- column types, numeric precision,
 * enum values and nullability -- rather than a hand translation of
 * prisma/schema.prisma.
 *
 * Two deliberate edits after generation:
 *   - timestamp and date columns use mode: 'date'. Introspection defaults them
 *     to 'string', but Prisma returned Date objects and the services call
 *     .toISOString() on them, so strings would fail at runtime, not at build.
 *   - the _prisma_migrations bookkeeping table is dropped; it is not domain data.
 *   - every `id` primary key carries $defaultFn(randomUUID). Prisma's
 *     @default(uuid()) was applied by the Prisma client, NOT by the database --
 *     all 41 id columns have no column_default in Postgres -- so without this
 *     every insert fails on a null primary key.
 *   - updated_at columns carry $defaultFn + $onUpdate. Prisma's @updatedAt set
 *     these on both insert and update; Drizzle does nothing unless the column
 *     says so, and they are NOT NULL with no database default, so inserts would
 *     fail and updates would silently leave a stale timestamp.
 *
 * Regenerate with: npm run db:pull
 */
import { pgTable, varchar, timestamp, text, integer, jsonb, uniqueIndex, foreignKey, boolean, index, numeric, date, pgEnum } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"
import { randomUUID } from "node:crypto"

export const bookingSource = pgEnum("BookingSource", ['website', 'mobile_app', 'admin', 'agent', 'walk_in', 'api'])
export const bookingStatus = pgEnum("BookingStatus", ['pending', 'held', 'confirmed', 'checked_in', 'checked_out', 'cancelled', 'completed', 'no_show'])
export const commissionStatus = pgEnum("CommissionStatus", ['pending', 'approved', 'paid', 'cancelled'])
export const entityStatus = pgEnum("EntityStatus", ['active', 'inactive'])
export const hotelStatus = pgEnum("HotelStatus", ['active', 'inactive', 'suspended'])
export const invoiceStatus = pgEnum("InvoiceStatus", ['unpaid', 'partially_paid', 'paid', 'void'])
export const notificationChannel = pgEnum("NotificationChannel", ['email', 'in_app', 'sms', 'whatsapp'])
export const paymentMethod = pgEnum("PaymentMethod", ['cash', 'bank_transfer', 'card', 'mobile_banking', 'online_gateway'])
export const paymentStatus = pgEnum("PaymentStatus", ['pending', 'processing', 'paid', 'failed', 'refunded', 'partially_refunded'])
export const ratePlanType = pgEnum("RatePlanType", ['room_only', 'breakfast_included', 'half_board', 'full_board', 'all_inclusive'])
export const refundStatus = pgEnum("RefundStatus", ['pending', 'processing', 'completed', 'rejected'])
export const roomStatus = pgEnum("RoomStatus", ['available', 'occupied', 'maintenance', 'inactive'])
export const tourBookingStatus = pgEnum("TourBookingStatus", ['pending', 'confirmed', 'cancelled', 'completed'])
export const transportBookingStatus = pgEnum("TransportBookingStatus", ['pending', 'confirmed', 'in_progress', 'completed', 'cancelled'])
export const vehicleStatus = pgEnum("VehicleStatus", ['available', 'in_use', 'maintenance', 'inactive'])
export const vehicleType = pgEnum("VehicleType", ['car', 'microbus', 'bus', 'van', 'minibus'])


export const emailLogs = pgTable("email_logs", {
	id: text().primaryKey().notNull().$defaultFn(() => randomUUID()),
	toEmail: text("to_email").notNull(),
	template: text().notNull(),
	subject: text().notNull(),
	status: text().notNull(),
	error: text(),
	metadata: jsonb(),
	createdAt: timestamp("created_at", { precision: 3, mode: 'date' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
});

export const agencies = pgTable("agencies", {
	id: text().primaryKey().notNull().$defaultFn(() => randomUUID()),
	name: text().notNull(),
	legalName: text("legal_name"),
	email: text(),
	phone: text(),
	address: text(),
	logoUrl: text("logo_url"),
	currency: text().default('USD').notNull(),
	timezone: text().default('UTC').notNull(),
	status: entityStatus().default('active').notNull(),
	createdAt: timestamp("created_at", { precision: 3, mode: 'date' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
	updatedAt: timestamp("updated_at", { precision: 3, mode: 'date' }).notNull().$defaultFn(() => new Date()).$onUpdate(() => new Date()),
});

export const users = pgTable("users", {
	id: text().primaryKey().notNull().$defaultFn(() => randomUUID()),
	agencyId: text("agency_id"),
	firstName: text("first_name").notNull(),
	lastName: text("last_name").notNull(),
	email: text().notNull(),
	phone: text(),
	passwordHash: text("password_hash").notNull(),
	isEmailVerified: boolean("is_email_verified").default(false).notNull(),
	emailVerifyToken: text("email_verify_token"),
	emailVerifyExpires: timestamp("email_verify_expires", { precision: 3, mode: 'date' }),
	passwordResetToken: text("password_reset_token"),
	passwordResetExpires: timestamp("password_reset_expires", { precision: 3, mode: 'date' }),
	refreshTokenHash: text("refresh_token_hash"),
	status: entityStatus().default('active').notNull(),
	lastLoginAt: timestamp("last_login_at", { precision: 3, mode: 'date' }),
	deletedAt: timestamp("deleted_at", { precision: 3, mode: 'date' }),
	createdAt: timestamp("created_at", { precision: 3, mode: 'date' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
	updatedAt: timestamp("updated_at", { precision: 3, mode: 'date' }).notNull().$defaultFn(() => new Date()).$onUpdate(() => new Date()),
}, (table) => [
	uniqueIndex("users_email_key").using("btree", table.email.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.agencyId],
			foreignColumns: [agencies.id],
			name: "users_agency_id_fkey"
		}).onUpdate("cascade").onDelete("set null"),
]);

export const userRoles = pgTable("user_roles", {
	id: text().primaryKey().notNull().$defaultFn(() => randomUUID()),
	userId: text("user_id").notNull(),
	roleId: text("role_id").notNull(),
	createdAt: timestamp("created_at", { precision: 3, mode: 'date' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
}, (table) => [
	uniqueIndex("user_roles_user_id_role_id_key").using("btree", table.userId.asc().nullsLast().op("text_ops"), table.roleId.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [users.id],
			name: "user_roles_user_id_fkey"
		}).onUpdate("cascade").onDelete("cascade"),
	foreignKey({
			columns: [table.roleId],
			foreignColumns: [roles.id],
			name: "user_roles_role_id_fkey"
		}).onUpdate("cascade").onDelete("cascade"),
]);

export const roles = pgTable("roles", {
	id: text().primaryKey().notNull().$defaultFn(() => randomUUID()),
	name: text().notNull(),
	description: text(),
	isSystem: boolean("is_system").default(false).notNull(),
	createdAt: timestamp("created_at", { precision: 3, mode: 'date' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
	updatedAt: timestamp("updated_at", { precision: 3, mode: 'date' }).notNull().$defaultFn(() => new Date()).$onUpdate(() => new Date()),
}, (table) => [
	uniqueIndex("roles_name_key").using("btree", table.name.asc().nullsLast().op("text_ops")),
]);

export const rolePermissions = pgTable("role_permissions", {
	id: text().primaryKey().notNull().$defaultFn(() => randomUUID()),
	roleId: text("role_id").notNull(),
	permissionId: text("permission_id").notNull(),
	createdAt: timestamp("created_at", { precision: 3, mode: 'date' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
}, (table) => [
	uniqueIndex("role_permissions_role_id_permission_id_key").using("btree", table.roleId.asc().nullsLast().op("text_ops"), table.permissionId.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.roleId],
			foreignColumns: [roles.id],
			name: "role_permissions_role_id_fkey"
		}).onUpdate("cascade").onDelete("cascade"),
	foreignKey({
			columns: [table.permissionId],
			foreignColumns: [permissions.id],
			name: "role_permissions_permission_id_fkey"
		}).onUpdate("cascade").onDelete("cascade"),
]);

export const permissions = pgTable("permissions", {
	id: text().primaryKey().notNull().$defaultFn(() => randomUUID()),
	name: text().notNull(),
	module: text().notNull(),
	description: text(),
	createdAt: timestamp("created_at", { precision: 3, mode: 'date' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
}, (table) => [
	uniqueIndex("permissions_name_key").using("btree", table.name.asc().nullsLast().op("text_ops")),
]);

export const hotels = pgTable("hotels", {
	id: text().primaryKey().notNull().$defaultFn(() => randomUUID()),
	agencyId: text("agency_id"),
	name: text().notNull(),
	description: text(),
	address: text(),
	city: text(),
	state: text(),
	country: text(),
	postalCode: text("postal_code"),
	latitude: numeric({ precision: 9, scale:  6 }),
	longitude: numeric({ precision: 9, scale:  6 }),
	starRating: integer("star_rating"),
	email: text(),
	phone: text(),
	checkInTime: text("check_in_time").default('14:00').notNull(),
	checkOutTime: text("check_out_time").default('12:00').notNull(),
	cancellationPolicy: text("cancellation_policy"),
	paymentPolicy: text("payment_policy"),
	childPolicy: text("child_policy"),
	petPolicy: text("pet_policy"),
	status: hotelStatus().default('active').notNull(),
	deletedAt: timestamp("deleted_at", { precision: 3, mode: 'date' }),
	createdAt: timestamp("created_at", { precision: 3, mode: 'date' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
	updatedAt: timestamp("updated_at", { precision: 3, mode: 'date' }).notNull().$defaultFn(() => new Date()).$onUpdate(() => new Date()),
}, (table) => [
	index("hotels_city_country_idx").using("btree", table.city.asc().nullsLast().op("text_ops"), table.country.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.agencyId],
			foreignColumns: [agencies.id],
			name: "hotels_agency_id_fkey"
		}).onUpdate("cascade").onDelete("set null"),
]);

export const hotelImages = pgTable("hotel_images", {
	id: text().primaryKey().notNull().$defaultFn(() => randomUUID()),
	hotelId: text("hotel_id").notNull(),
	url: text().notNull(),
	caption: text(),
	isPrimary: boolean("is_primary").default(false).notNull(),
	sortOrder: integer("sort_order").default(0).notNull(),
	createdAt: timestamp("created_at", { precision: 3, mode: 'date' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
}, (table) => [
	foreignKey({
			columns: [table.hotelId],
			foreignColumns: [hotels.id],
			name: "hotel_images_hotel_id_fkey"
		}).onUpdate("cascade").onDelete("cascade"),
]);

export const hotelAmenities = pgTable("hotel_amenities", {
	id: text().primaryKey().notNull().$defaultFn(() => randomUUID()),
	hotelId: text("hotel_id").notNull(),
	amenityId: text("amenity_id").notNull(),
}, (table) => [
	uniqueIndex("hotel_amenities_hotel_id_amenity_id_key").using("btree", table.hotelId.asc().nullsLast().op("text_ops"), table.amenityId.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.hotelId],
			foreignColumns: [hotels.id],
			name: "hotel_amenities_hotel_id_fkey"
		}).onUpdate("cascade").onDelete("cascade"),
	foreignKey({
			columns: [table.amenityId],
			foreignColumns: [amenities.id],
			name: "hotel_amenities_amenity_id_fkey"
		}).onUpdate("cascade").onDelete("cascade"),
]);

export const amenities = pgTable("amenities", {
	id: text().primaryKey().notNull().$defaultFn(() => randomUUID()),
	name: text().notNull(),
	icon: text(),
	category: text(),
	createdAt: timestamp("created_at", { precision: 3, mode: 'date' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
}, (table) => [
	uniqueIndex("amenities_name_key").using("btree", table.name.asc().nullsLast().op("text_ops")),
]);

export const roomTypes = pgTable("room_types", {
	id: text().primaryKey().notNull().$defaultFn(() => randomUUID()),
	hotelId: text("hotel_id").notNull(),
	name: text().notNull(),
	description: text(),
	maxAdults: integer("max_adults").default(2).notNull(),
	maxChildren: integer("max_children").default(0).notNull(),
	bedType: text("bed_type"),
	roomSize: numeric("room_size", { precision: 6, scale:  2 }),
	smoking: boolean().default(false).notNull(),
	totalRooms: integer("total_rooms").default(0).notNull(),
	deletedAt: timestamp("deleted_at", { precision: 3, mode: 'date' }),
	createdAt: timestamp("created_at", { precision: 3, mode: 'date' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
	updatedAt: timestamp("updated_at", { precision: 3, mode: 'date' }).notNull().$defaultFn(() => new Date()).$onUpdate(() => new Date()),
}, (table) => [
	foreignKey({
			columns: [table.hotelId],
			foreignColumns: [hotels.id],
			name: "room_types_hotel_id_fkey"
		}).onUpdate("cascade").onDelete("cascade"),
]);

export const roomTypeImages = pgTable("room_type_images", {
	id: text().primaryKey().notNull().$defaultFn(() => randomUUID()),
	roomTypeId: text("room_type_id").notNull(),
	url: text().notNull(),
	caption: text(),
	sortOrder: integer("sort_order").default(0).notNull(),
	createdAt: timestamp("created_at", { precision: 3, mode: 'date' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
}, (table) => [
	foreignKey({
			columns: [table.roomTypeId],
			foreignColumns: [roomTypes.id],
			name: "room_type_images_room_type_id_fkey"
		}).onUpdate("cascade").onDelete("cascade"),
]);

export const roomTypeAmenities = pgTable("room_type_amenities", {
	id: text().primaryKey().notNull().$defaultFn(() => randomUUID()),
	roomTypeId: text("room_type_id").notNull(),
	amenityId: text("amenity_id").notNull(),
}, (table) => [
	uniqueIndex("room_type_amenities_room_type_id_amenity_id_key").using("btree", table.roomTypeId.asc().nullsLast().op("text_ops"), table.amenityId.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.roomTypeId],
			foreignColumns: [roomTypes.id],
			name: "room_type_amenities_room_type_id_fkey"
		}).onUpdate("cascade").onDelete("cascade"),
	foreignKey({
			columns: [table.amenityId],
			foreignColumns: [amenities.id],
			name: "room_type_amenities_amenity_id_fkey"
		}).onUpdate("cascade").onDelete("cascade"),
]);

export const rooms = pgTable("rooms", {
	id: text().primaryKey().notNull().$defaultFn(() => randomUUID()),
	roomTypeId: text("room_type_id").notNull(),
	roomNumber: text("room_number").notNull(),
	floor: text(),
	status: roomStatus().default('available').notNull(),
	deletedAt: timestamp("deleted_at", { precision: 3, mode: 'date' }),
	createdAt: timestamp("created_at", { precision: 3, mode: 'date' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
	updatedAt: timestamp("updated_at", { precision: 3, mode: 'date' }).notNull().$defaultFn(() => new Date()).$onUpdate(() => new Date()),
}, (table) => [
	uniqueIndex("rooms_room_type_id_room_number_key").using("btree", table.roomTypeId.asc().nullsLast().op("text_ops"), table.roomNumber.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.roomTypeId],
			foreignColumns: [roomTypes.id],
			name: "rooms_room_type_id_fkey"
		}).onUpdate("cascade").onDelete("cascade"),
]);

export const roomRates = pgTable("room_rates", {
	id: text().primaryKey().notNull().$defaultFn(() => randomUUID()),
	roomTypeId: text("room_type_id").notNull(),
	ratePlanId: text("rate_plan_id").notNull(),
	startDate: date("start_date", { mode: 'date' }).notNull(),
	endDate: date("end_date", { mode: 'date' }).notNull(),
	price: numeric({ precision: 12, scale:  2 }).notNull(),
	extraAdultPrice: numeric("extra_adult_price", { precision: 12, scale:  2 }).default('0').notNull(),
	extraChildPrice: numeric("extra_child_price", { precision: 12, scale:  2 }).default('0').notNull(),
	currency: text().default('USD').notNull(),
	priority: integer().default(0).notNull(),
	createdAt: timestamp("created_at", { precision: 3, mode: 'date' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
	updatedAt: timestamp("updated_at", { precision: 3, mode: 'date' }).notNull().$defaultFn(() => new Date()).$onUpdate(() => new Date()),
}, (table) => [
	index("room_rates_room_type_id_start_date_end_date_idx").using("btree", table.roomTypeId.asc().nullsLast().op("date_ops"), table.startDate.asc().nullsLast().op("text_ops"), table.endDate.asc().nullsLast().op("date_ops")),
	foreignKey({
			columns: [table.roomTypeId],
			foreignColumns: [roomTypes.id],
			name: "room_rates_room_type_id_fkey"
		}).onUpdate("cascade").onDelete("cascade"),
	foreignKey({
			columns: [table.ratePlanId],
			foreignColumns: [ratePlans.id],
			name: "room_rates_rate_plan_id_fkey"
		}).onUpdate("cascade").onDelete("cascade"),
]);

export const ratePlans = pgTable("rate_plans", {
	id: text().primaryKey().notNull().$defaultFn(() => randomUUID()),
	name: text().notNull(),
	type: ratePlanType().default('room_only').notNull(),
	description: text(),
	createdAt: timestamp("created_at", { precision: 3, mode: 'date' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
	updatedAt: timestamp("updated_at", { precision: 3, mode: 'date' }).notNull().$defaultFn(() => new Date()).$onUpdate(() => new Date()),
});

export const customers = pgTable("customers", {
	id: text().primaryKey().notNull().$defaultFn(() => randomUUID()),
	userId: text("user_id"),
	firstName: text("first_name").notNull(),
	lastName: text("last_name").notNull(),
	email: text().notNull(),
	phone: text(),
	address: text(),
	nationality: text(),
	passportNumber: text("passport_number"),
	passportExpiry: date("passport_expiry", { mode: 'date' }),
	dateOfBirth: date("date_of_birth", { mode: 'date' }),
	deletedAt: timestamp("deleted_at", { precision: 3, mode: 'date' }),
	createdAt: timestamp("created_at", { precision: 3, mode: 'date' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
	updatedAt: timestamp("updated_at", { precision: 3, mode: 'date' }).notNull().$defaultFn(() => new Date()).$onUpdate(() => new Date()),
}, (table) => [
	uniqueIndex("customers_email_key").using("btree", table.email.asc().nullsLast().op("text_ops")),
	uniqueIndex("customers_user_id_key").using("btree", table.userId.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [users.id],
			name: "customers_user_id_fkey"
		}).onUpdate("cascade").onDelete("set null"),
]);

export const customerDocuments = pgTable("customer_documents", {
	id: text().primaryKey().notNull().$defaultFn(() => randomUUID()),
	customerId: text("customer_id").notNull(),
	type: text().notNull(),
	fileUrl: text("file_url").notNull(),
	createdAt: timestamp("created_at", { precision: 3, mode: 'date' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
}, (table) => [
	foreignKey({
			columns: [table.customerId],
			foreignColumns: [customers.id],
			name: "customer_documents_customer_id_fkey"
		}).onUpdate("cascade").onDelete("cascade"),
]);

export const bookings = pgTable("bookings", {
	id: text().primaryKey().notNull().$defaultFn(() => randomUUID()),
	bookingNumber: text("booking_number").notNull(),
	hotelId: text("hotel_id").notNull(),
	customerId: text("customer_id").notNull(),
	agentId: text("agent_id"),
	checkIn: date("check_in", { mode: 'date' }).notNull(),
	checkOut: date("check_out", { mode: 'date' }).notNull(),
	adults: integer().default(1).notNull(),
	children: integer().default(0).notNull(),
	specialRequests: text("special_requests"),
	status: bookingStatus().default('pending').notNull(),
	source: bookingSource().default('website').notNull(),
	currency: text().default('USD').notNull(),
	subtotal: numeric({ precision: 12, scale:  2 }).default('0').notNull(),
	discountAmount: numeric("discount_amount", { precision: 12, scale:  2 }).default('0').notNull(),
	taxAmount: numeric("tax_amount", { precision: 12, scale:  2 }).default('0').notNull(),
	commissionAmount: numeric("commission_amount", { precision: 12, scale:  2 }).default('0').notNull(),
	totalAmount: numeric("total_amount", { precision: 12, scale:  2 }).default('0').notNull(),
	paidAmount: numeric("paid_amount", { precision: 12, scale:  2 }).default('0').notNull(),
	dueAmount: numeric("due_amount", { precision: 12, scale:  2 }).default('0').notNull(),
	holdExpiresAt: timestamp("hold_expires_at", { precision: 3, mode: 'date' }),
	cancelledAt: timestamp("cancelled_at", { precision: 3, mode: 'date' }),
	cancellationFee: numeric("cancellation_fee", { precision: 12, scale:  2 }),
	refundableAmount: numeric("refundable_amount", { precision: 12, scale:  2 }),
	cancellationReason: text("cancellation_reason"),
	createdAt: timestamp("created_at", { precision: 3, mode: 'date' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
	updatedAt: timestamp("updated_at", { precision: 3, mode: 'date' }).notNull().$defaultFn(() => new Date()).$onUpdate(() => new Date()),
}, (table) => [
	uniqueIndex("bookings_booking_number_key").using("btree", table.bookingNumber.asc().nullsLast().op("text_ops")),
	index("bookings_check_in_check_out_idx").using("btree", table.checkIn.asc().nullsLast().op("date_ops"), table.checkOut.asc().nullsLast().op("date_ops")),
	index("bookings_status_idx").using("btree", table.status.asc().nullsLast().op("enum_ops")),
	foreignKey({
			columns: [table.hotelId],
			foreignColumns: [hotels.id],
			name: "bookings_hotel_id_fkey"
		}).onUpdate("cascade").onDelete("restrict"),
	foreignKey({
			columns: [table.customerId],
			foreignColumns: [customers.id],
			name: "bookings_customer_id_fkey"
		}).onUpdate("cascade").onDelete("restrict"),
	foreignKey({
			columns: [table.agentId],
			foreignColumns: [users.id],
			name: "bookings_agent_id_fkey"
		}).onUpdate("cascade").onDelete("set null"),
]);

export const bookingRooms = pgTable("booking_rooms", {
	id: text().primaryKey().notNull().$defaultFn(() => randomUUID()),
	bookingId: text("booking_id").notNull(),
	roomId: text("room_id").notNull(),
	roomTypeId: text("room_type_id").notNull(),
	checkIn: date("check_in", { mode: 'date' }).notNull(),
	checkOut: date("check_out", { mode: 'date' }).notNull(),
	nights: integer().notNull(),
	ratePerNight: numeric("rate_per_night", { precision: 12, scale:  2 }).notNull(),
	totalPrice: numeric("total_price", { precision: 12, scale:  2 }).notNull(),
	actualCheckIn: timestamp("actual_check_in", { precision: 3, mode: 'date' }),
	actualCheckOut: timestamp("actual_check_out", { precision: 3, mode: 'date' }),
	checkedInById: text("checked_in_by_id"),
	checkedOutById: text("checked_out_by_id"),
	notes: text(),
	createdAt: timestamp("created_at", { precision: 3, mode: 'date' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
	updatedAt: timestamp("updated_at", { precision: 3, mode: 'date' }).notNull().$defaultFn(() => new Date()).$onUpdate(() => new Date()),
}, (table) => [
	index("booking_rooms_room_id_check_in_check_out_idx").using("btree", table.roomId.asc().nullsLast().op("date_ops"), table.checkIn.asc().nullsLast().op("text_ops"), table.checkOut.asc().nullsLast().op("date_ops")),
	foreignKey({
			columns: [table.bookingId],
			foreignColumns: [bookings.id],
			name: "booking_rooms_booking_id_fkey"
		}).onUpdate("cascade").onDelete("cascade"),
	foreignKey({
			columns: [table.roomId],
			foreignColumns: [rooms.id],
			name: "booking_rooms_room_id_fkey"
		}).onUpdate("cascade").onDelete("restrict"),
	foreignKey({
			columns: [table.roomTypeId],
			foreignColumns: [roomTypes.id],
			name: "booking_rooms_room_type_id_fkey"
		}).onUpdate("cascade").onDelete("restrict"),
	foreignKey({
			columns: [table.checkedInById],
			foreignColumns: [users.id],
			name: "booking_rooms_checked_in_by_id_fkey"
		}).onUpdate("cascade").onDelete("set null"),
	foreignKey({
			columns: [table.checkedOutById],
			foreignColumns: [users.id],
			name: "booking_rooms_checked_out_by_id_fkey"
		}).onUpdate("cascade").onDelete("set null"),
]);

export const bookingGuests = pgTable("booking_guests", {
	id: text().primaryKey().notNull().$defaultFn(() => randomUUID()),
	bookingId: text("booking_id").notNull(),
	firstName: text("first_name").notNull(),
	lastName: text("last_name").notNull(),
	email: text(),
	phone: text(),
	dateOfBirth: date("date_of_birth", { mode: 'date' }),
	nationality: text(),
	passportNumber: text("passport_number"),
	passportExpiry: date("passport_expiry", { mode: 'date' }),
	address: text(),
	specialRequirements: text("special_requirements"),
	isPrimary: boolean("is_primary").default(false).notNull(),
	createdAt: timestamp("created_at", { precision: 3, mode: 'date' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
}, (table) => [
	foreignKey({
			columns: [table.bookingId],
			foreignColumns: [bookings.id],
			name: "booking_guests_booking_id_fkey"
		}).onUpdate("cascade").onDelete("cascade"),
]);

export const bookingServices = pgTable("booking_services", {
	id: text().primaryKey().notNull().$defaultFn(() => randomUUID()),
	bookingId: text("booking_id").notNull(),
	serviceId: text("service_id").notNull(),
	quantity: integer().default(1).notNull(),
	price: numeric({ precision: 12, scale:  2 }).notNull(),
	tax: numeric({ precision: 12, scale:  2 }).default('0').notNull(),
	total: numeric({ precision: 12, scale:  2 }).notNull(),
	createdAt: timestamp("created_at", { precision: 3, mode: 'date' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
}, (table) => [
	foreignKey({
			columns: [table.bookingId],
			foreignColumns: [bookings.id],
			name: "booking_services_booking_id_fkey"
		}).onUpdate("cascade").onDelete("cascade"),
	foreignKey({
			columns: [table.serviceId],
			foreignColumns: [services.id],
			name: "booking_services_service_id_fkey"
		}).onUpdate("cascade").onDelete("restrict"),
]);

export const services = pgTable("services", {
	id: text().primaryKey().notNull().$defaultFn(() => randomUUID()),
	name: text().notNull(),
	description: text(),
	price: numeric({ precision: 12, scale:  2 }).notNull(),
	tax: numeric({ precision: 12, scale:  2 }).default('0').notNull(),
	status: entityStatus().default('active').notNull(),
	createdAt: timestamp("created_at", { precision: 3, mode: 'date' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
	updatedAt: timestamp("updated_at", { precision: 3, mode: 'date' }).notNull().$defaultFn(() => new Date()).$onUpdate(() => new Date()),
});

export const bookingStatusHistory = pgTable("booking_status_history", {
	id: text().primaryKey().notNull().$defaultFn(() => randomUUID()),
	bookingId: text("booking_id").notNull(),
	fromStatus: bookingStatus("from_status"),
	toStatus: bookingStatus("to_status").notNull(),
	changedById: text("changed_by_id"),
	reason: text(),
	createdAt: timestamp("created_at", { precision: 3, mode: 'date' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
}, (table) => [
	foreignKey({
			columns: [table.bookingId],
			foreignColumns: [bookings.id],
			name: "booking_status_history_booking_id_fkey"
		}).onUpdate("cascade").onDelete("cascade"),
	foreignKey({
			columns: [table.changedById],
			foreignColumns: [users.id],
			name: "booking_status_history_changed_by_id_fkey"
		}).onUpdate("cascade").onDelete("set null"),
]);

export const payments = pgTable("payments", {
	id: text().primaryKey().notNull().$defaultFn(() => randomUUID()),
	bookingId: text("booking_id").notNull(),
	transactionId: text("transaction_id"),
	amount: numeric({ precision: 12, scale:  2 }).notNull(),
	currency: text().default('USD').notNull(),
	method: paymentMethod().notNull(),
	gateway: text(),
	status: paymentStatus().default('pending').notNull(),
	paidAt: timestamp("paid_at", { precision: 3, mode: 'date' }),
	metadata: jsonb(),
	createdAt: timestamp("created_at", { precision: 3, mode: 'date' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
	updatedAt: timestamp("updated_at", { precision: 3, mode: 'date' }).notNull().$defaultFn(() => new Date()).$onUpdate(() => new Date()),
}, (table) => [
	foreignKey({
			columns: [table.bookingId],
			foreignColumns: [bookings.id],
			name: "payments_booking_id_fkey"
		}).onUpdate("cascade").onDelete("restrict"),
]);

export const refunds = pgTable("refunds", {
	id: text().primaryKey().notNull().$defaultFn(() => randomUUID()),
	paymentId: text("payment_id").notNull(),
	amount: numeric({ precision: 12, scale:  2 }).notNull(),
	reason: text(),
	status: refundStatus().default('pending').notNull(),
	processedAt: timestamp("processed_at", { precision: 3, mode: 'date' }),
	createdAt: timestamp("created_at", { precision: 3, mode: 'date' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
	updatedAt: timestamp("updated_at", { precision: 3, mode: 'date' }).notNull().$defaultFn(() => new Date()).$onUpdate(() => new Date()),
}, (table) => [
	foreignKey({
			columns: [table.paymentId],
			foreignColumns: [payments.id],
			name: "refunds_payment_id_fkey"
		}).onUpdate("cascade").onDelete("restrict"),
]);

export const invoices = pgTable("invoices", {
	id: text().primaryKey().notNull().$defaultFn(() => randomUUID()),
	invoiceNumber: text("invoice_number").notNull(),
	bookingId: text("booking_id").notNull(),
	subtotal: numeric({ precision: 12, scale:  2 }).notNull(),
	discountAmount: numeric("discount_amount", { precision: 12, scale:  2 }).default('0').notNull(),
	taxAmount: numeric("tax_amount", { precision: 12, scale:  2 }).default('0').notNull(),
	totalAmount: numeric("total_amount", { precision: 12, scale:  2 }).notNull(),
	paidAmount: numeric("paid_amount", { precision: 12, scale:  2 }).default('0').notNull(),
	dueAmount: numeric("due_amount", { precision: 12, scale:  2 }).default('0').notNull(),
	currency: text().default('USD').notNull(),
	status: invoiceStatus().default('unpaid').notNull(),
	pdfUrl: text("pdf_url"),
	issuedAt: timestamp("issued_at", { precision: 3, mode: 'date' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
	createdAt: timestamp("created_at", { precision: 3, mode: 'date' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
	updatedAt: timestamp("updated_at", { precision: 3, mode: 'date' }).notNull().$defaultFn(() => new Date()).$onUpdate(() => new Date()),
}, (table) => [
	uniqueIndex("invoices_invoice_number_key").using("btree", table.invoiceNumber.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.bookingId],
			foreignColumns: [bookings.id],
			name: "invoices_booking_id_fkey"
		}).onUpdate("cascade").onDelete("restrict"),
]);

export const invoiceItems = pgTable("invoice_items", {
	id: text().primaryKey().notNull().$defaultFn(() => randomUUID()),
	invoiceId: text("invoice_id").notNull(),
	description: text().notNull(),
	quantity: integer().default(1).notNull(),
	unitPrice: numeric("unit_price", { precision: 12, scale:  2 }).notNull(),
	total: numeric({ precision: 12, scale:  2 }).notNull(),
}, (table) => [
	foreignKey({
			columns: [table.invoiceId],
			foreignColumns: [invoices.id],
			name: "invoice_items_invoice_id_fkey"
		}).onUpdate("cascade").onDelete("cascade"),
]);

export const destinations = pgTable("destinations", {
	id: text().primaryKey().notNull().$defaultFn(() => randomUUID()),
	name: text().notNull(),
	country: text(),
	description: text(),
	imageUrl: text("image_url"),
	status: entityStatus().default('active').notNull(),
	deletedAt: timestamp("deleted_at", { precision: 3, mode: 'date' }),
	createdAt: timestamp("created_at", { precision: 3, mode: 'date' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
	updatedAt: timestamp("updated_at", { precision: 3, mode: 'date' }).notNull().$defaultFn(() => new Date()).$onUpdate(() => new Date()),
});

export const tourPackages = pgTable("tour_packages", {
	id: text().primaryKey().notNull().$defaultFn(() => randomUUID()),
	destinationId: text("destination_id").notNull(),
	name: text().notNull(),
	description: text(),
	durationDays: integer("duration_days").notNull(),
	price: numeric({ precision: 12, scale:  2 }).notNull(),
	currency: text().default('USD').notNull(),
	maxParticipants: integer("max_participants").notNull(),
	includedServices: text("included_services"),
	excludedServices: text("excluded_services"),
	status: entityStatus().default('active').notNull(),
	deletedAt: timestamp("deleted_at", { precision: 3, mode: 'date' }),
	createdAt: timestamp("created_at", { precision: 3, mode: 'date' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
	updatedAt: timestamp("updated_at", { precision: 3, mode: 'date' }).notNull().$defaultFn(() => new Date()).$onUpdate(() => new Date()),
}, (table) => [
	foreignKey({
			columns: [table.destinationId],
			foreignColumns: [destinations.id],
			name: "tour_packages_destination_id_fkey"
		}).onUpdate("cascade").onDelete("restrict"),
]);

export const tourImages = pgTable("tour_images", {
	id: text().primaryKey().notNull().$defaultFn(() => randomUUID()),
	tourPackageId: text("tour_package_id").notNull(),
	url: text().notNull(),
	caption: text(),
	sortOrder: integer("sort_order").default(0).notNull(),
	createdAt: timestamp("created_at", { precision: 3, mode: 'date' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
}, (table) => [
	foreignKey({
			columns: [table.tourPackageId],
			foreignColumns: [tourPackages.id],
			name: "tour_images_tour_package_id_fkey"
		}).onUpdate("cascade").onDelete("cascade"),
]);

export const tourItineraries = pgTable("tour_itineraries", {
	id: text().primaryKey().notNull().$defaultFn(() => randomUUID()),
	tourPackageId: text("tour_package_id").notNull(),
	dayNumber: integer("day_number").notNull(),
	title: text().notNull(),
	description: text(),
	activities: text(),
	meals: text(),
	accommodation: text(),
	transportation: text(),
}, (table) => [
	uniqueIndex("tour_itineraries_tour_package_id_day_number_key").using("btree", table.tourPackageId.asc().nullsLast().op("int4_ops"), table.dayNumber.asc().nullsLast().op("int4_ops")),
	foreignKey({
			columns: [table.tourPackageId],
			foreignColumns: [tourPackages.id],
			name: "tour_itineraries_tour_package_id_fkey"
		}).onUpdate("cascade").onDelete("cascade"),
]);

export const tourBookings = pgTable("tour_bookings", {
	id: text().primaryKey().notNull().$defaultFn(() => randomUUID()),
	bookingNumber: text("booking_number").notNull(),
	tourPackageId: text("tour_package_id").notNull(),
	customerId: text("customer_id").notNull(),
	participants: integer().notNull(),
	travelDate: date("travel_date", { mode: 'date' }).notNull(),
	price: numeric({ precision: 12, scale:  2 }).notNull(),
	discountAmount: numeric("discount_amount", { precision: 12, scale:  2 }).default('0').notNull(),
	taxAmount: numeric("tax_amount", { precision: 12, scale:  2 }).default('0').notNull(),
	totalAmount: numeric("total_amount", { precision: 12, scale:  2 }).notNull(),
	paidAmount: numeric("paid_amount", { precision: 12, scale:  2 }).default('0').notNull(),
	currency: text().default('USD').notNull(),
	status: tourBookingStatus().default('pending').notNull(),
	createdAt: timestamp("created_at", { precision: 3, mode: 'date' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
	updatedAt: timestamp("updated_at", { precision: 3, mode: 'date' }).notNull().$defaultFn(() => new Date()).$onUpdate(() => new Date()),
}, (table) => [
	uniqueIndex("tour_bookings_booking_number_key").using("btree", table.bookingNumber.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.tourPackageId],
			foreignColumns: [tourPackages.id],
			name: "tour_bookings_tour_package_id_fkey"
		}).onUpdate("cascade").onDelete("restrict"),
	foreignKey({
			columns: [table.customerId],
			foreignColumns: [customers.id],
			name: "tour_bookings_customer_id_fkey"
		}).onUpdate("cascade").onDelete("restrict"),
]);

export const vehicles = pgTable("vehicles", {
	id: text().primaryKey().notNull().$defaultFn(() => randomUUID()),
	type: vehicleType().notNull(),
	registrationNumber: text("registration_number").notNull(),
	capacity: integer().notNull(),
	status: vehicleStatus().default('available').notNull(),
	deletedAt: timestamp("deleted_at", { precision: 3, mode: 'date' }),
	createdAt: timestamp("created_at", { precision: 3, mode: 'date' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
	updatedAt: timestamp("updated_at", { precision: 3, mode: 'date' }).notNull().$defaultFn(() => new Date()).$onUpdate(() => new Date()),
}, (table) => [
	uniqueIndex("vehicles_registration_number_key").using("btree", table.registrationNumber.asc().nullsLast().op("text_ops")),
]);

export const drivers = pgTable("drivers", {
	id: text().primaryKey().notNull().$defaultFn(() => randomUUID()),
	vehicleId: text("vehicle_id"),
	name: text().notNull(),
	phone: text(),
	licenseNumber: text("license_number"),
	status: entityStatus().default('active').notNull(),
	createdAt: timestamp("created_at", { precision: 3, mode: 'date' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
	updatedAt: timestamp("updated_at", { precision: 3, mode: 'date' }).notNull().$defaultFn(() => new Date()).$onUpdate(() => new Date()),
}, (table) => [
	foreignKey({
			columns: [table.vehicleId],
			foreignColumns: [vehicles.id],
			name: "drivers_vehicle_id_fkey"
		}).onUpdate("cascade").onDelete("set null"),
]);

export const transportBookings = pgTable("transport_bookings", {
	id: text().primaryKey().notNull().$defaultFn(() => randomUUID()),
	bookingId: text("booking_id"),
	vehicleId: text("vehicle_id").notNull(),
	driverId: text("driver_id"),
	pickup: text().notNull(),
	dropoff: text().notNull(),
	date: date({ mode: 'date' }).notNull(),
	time: text().notNull(),
	price: numeric({ precision: 12, scale:  2 }).notNull(),
	status: transportBookingStatus().default('pending').notNull(),
	createdAt: timestamp("created_at", { precision: 3, mode: 'date' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
	updatedAt: timestamp("updated_at", { precision: 3, mode: 'date' }).notNull().$defaultFn(() => new Date()).$onUpdate(() => new Date()),
}, (table) => [
	foreignKey({
			columns: [table.vehicleId],
			foreignColumns: [vehicles.id],
			name: "transport_bookings_vehicle_id_fkey"
		}).onUpdate("cascade").onDelete("restrict"),
	foreignKey({
			columns: [table.driverId],
			foreignColumns: [drivers.id],
			name: "transport_bookings_driver_id_fkey"
		}).onUpdate("cascade").onDelete("set null"),
]);

export const commissions = pgTable("commissions", {
	id: text().primaryKey().notNull().$defaultFn(() => randomUUID()),
	agentId: text("agent_id").notNull(),
	bookingId: text("booking_id").notNull(),
	percentage: numeric({ precision: 5, scale:  2 }).notNull(),
	amount: numeric({ precision: 12, scale:  2 }).notNull(),
	status: commissionStatus().default('pending').notNull(),
	paidAt: timestamp("paid_at", { precision: 3, mode: 'date' }),
	createdAt: timestamp("created_at", { precision: 3, mode: 'date' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
	updatedAt: timestamp("updated_at", { precision: 3, mode: 'date' }).notNull().$defaultFn(() => new Date()).$onUpdate(() => new Date()),
}, (table) => [
	foreignKey({
			columns: [table.agentId],
			foreignColumns: [users.id],
			name: "commissions_agent_id_fkey"
		}).onUpdate("cascade").onDelete("restrict"),
	foreignKey({
			columns: [table.bookingId],
			foreignColumns: [bookings.id],
			name: "commissions_booking_id_fkey"
		}).onUpdate("cascade").onDelete("restrict"),
]);

export const notifications = pgTable("notifications", {
	id: text().primaryKey().notNull().$defaultFn(() => randomUUID()),
	userId: text("user_id").notNull(),
	channel: notificationChannel().default('in_app').notNull(),
	event: text().notNull(),
	title: text().notNull(),
	message: text().notNull(),
	isRead: boolean("is_read").default(false).notNull(),
	metadata: jsonb(),
	createdAt: timestamp("created_at", { precision: 3, mode: 'date' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
}, (table) => [
	foreignKey({
			columns: [table.userId],
			foreignColumns: [users.id],
			name: "notifications_user_id_fkey"
		}).onUpdate("cascade").onDelete("restrict"),
]);

export const auditLogs = pgTable("audit_logs", {
	id: text().primaryKey().notNull().$defaultFn(() => randomUUID()),
	userId: text("user_id"),
	action: text().notNull(),
	entity: text().notNull(),
	entityId: text("entity_id"),
	oldValue: jsonb("old_value"),
	newValue: jsonb("new_value"),
	ipAddress: text("ip_address"),
	userAgent: text("user_agent"),
	createdAt: timestamp("created_at", { precision: 3, mode: 'date' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
}, (table) => [
	index("audit_logs_entity_entity_id_idx").using("btree", table.entity.asc().nullsLast().op("text_ops"), table.entityId.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [users.id],
			name: "audit_logs_user_id_fkey"
		}).onUpdate("cascade").onDelete("set null"),
]);

export const settings = pgTable("settings", {
	id: text().primaryKey().notNull().$defaultFn(() => randomUUID()),
	agencyId: text("agency_id"),
	key: text().notNull(),
	value: jsonb().notNull(),
	createdAt: timestamp("created_at", { precision: 3, mode: 'date' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
	updatedAt: timestamp("updated_at", { precision: 3, mode: 'date' }).notNull().$defaultFn(() => new Date()).$onUpdate(() => new Date()),
}, (table) => [
	uniqueIndex("settings_agency_id_key_key").using("btree", table.agencyId.asc().nullsLast().op("text_ops"), table.key.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.agencyId],
			foreignColumns: [agencies.id],
			name: "settings_agency_id_fkey"
		}).onUpdate("cascade").onDelete("set null"),
]);
